<a href="https://colab.research.google.com/github/sandeepProject/ICTTestRepo/blob/main/Case_Study_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Basic Array Operations Convert the mpg column into a NumPy array and calculate:<br>
○ The mean, median, and standard deviation of mpg.<br>
○ The number of cars with mpg greater than 25.

In [2]:
# importing numpy and pandas
import numpy as np
import pandas as pd

In [4]:
# reading data from csv file
data=pd.read_csv('auto-mpg.csv')
data.head(4)

# convert the mpg column into numpy array
mpg_numpy_array=data['mpg'].to_numpy()

# calculate mean, median and standard deviation
data_mean = np.mean(mpg_numpy_array)
data_median= np.median(mpg_numpy_array)
data_std = np.std(mpg_numpy_array)
print(f'Mean : {data_mean:.2f} , Median : {data_median:.2f} , Standard Deviation : {data_std:.2f}')

# No: of cars with mpg >25
count =np.sum(mpg_numpy_array>25)
print(f'No: of cars with mpg >25 : {count}')


Mean : 23.51 , Median : 23.00 , Standard Deviation : 7.81
No: of cars with mpg >25 : 158


2. Filtering Using NumPy, filter all cars with more than 6 cylinders.<br> Return the corresponding car_name as a list.

In [5]:
checkpoint=data['cylinders']>6
car_name_array=data['car name'][checkpoint].to_numpy()
print(car_name_array)

['chevrolet chevelle malibu' 'buick skylark 320' 'plymouth satellite'
 'amc rebel sst' 'ford torino' 'ford galaxie 500' 'chevrolet impala'
 'plymouth fury iii' 'pontiac catalina' 'amc ambassador dpl'
 'dodge challenger se' "plymouth 'cuda 340" 'chevrolet monte carlo'
 'buick estate wagon (sw)' 'ford f250' 'chevy c20' 'dodge d200' 'hi 1200d'
 'chevrolet impala' 'pontiac catalina brougham' 'ford galaxie 500'
 'plymouth fury iii' 'dodge monaco (sw)' 'ford country squire (sw)'
 'pontiac safari (sw)' 'chevrolet impala' 'pontiac catalina'
 'plymouth fury iii' 'ford galaxie 500' 'amc ambassador sst'
 'mercury marquis' 'buick lesabre custom' 'oldsmobile delta 88 royale'
 'chrysler newport royal' 'amc matador (sw)'
 'chevrolet chevelle concours (sw)' 'ford gran torino (sw)'
 'plymouth satellite custom (sw)' 'buick century 350' 'amc matador'
 'chevrolet malibu' 'ford gran torino' 'dodge coronet custom'
 'mercury marquis brougham' 'chevrolet caprice classic' 'ford ltd'
 'plymouth fury gran sedan'

3. Statistical Analysis Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [6]:
# 25, 50 and 75th percentiles using numpy
weight_numpy_array=data['weight'].to_numpy()
quartile=np.percentile(weight_numpy_array,[25,50,75])
print(f"25th percentile of weight: {quartile[0]:.2f}")
print(f"50th percentile of weight: {quartile[1]:.2f}")
print(f"75th percentile of weight: {quartile[2]:.2f}")

25th percentile of weight: 2223.75
50th percentile of weight: 2803.50
75th percentile of weight: 3608.00


4. Array Manipulation Convert the acceleration column into a NumPy array and normalize its values (scale between 0 and 1).

In [7]:
acc_numpy_array=data['acceleration'].to_numpy()
# acc_min=np.min(acc_numpy_array)
# acc_max=np.max(acc_numpy_array)
# acc_numpy_array=(acc_numpy_array-acc_min)/(acc_max-acc_min)
normalized_acc=(acc_numpy_array-np.min(acc_numpy_array))/(np.max(acc_numpy_array)+np.min(acc_numpy_array))
print(np.round(normalized_acc,1))

[0.1 0.1 0.1 0.1 0.1 0.1 0.  0.  0.1 0.  0.1 0.  0.  0.1 0.2 0.2 0.2 0.2
 0.2 0.4 0.3 0.2 0.3 0.1 0.2 0.2 0.2 0.2 0.3 0.2 0.2 0.2 0.3 0.2 0.2 0.2
 0.2 0.2 0.1 0.1 0.2 0.2 0.1 0.1 0.1 0.2 0.3 0.2 0.2 0.2 0.2 0.4 0.2 0.3
 0.3 0.3 0.4 0.2 0.3 0.5 0.4 0.3 0.1 0.1 0.2 0.2 0.1 0.1 0.2 0.2 0.1 0.2
 0.1 0.2 0.2 0.2 0.2 0.3 0.4 0.3 0.2 0.3 0.2 0.2 0.3 0.2 0.1 0.2 0.2 0.1
 0.1 0.1 0.2 0.2 0.1 0.1 0.1 0.3 0.3 0.2 0.3 0.2 0.4 0.2 0.1 0.2 0.1 0.2
 0.3 0.4 0.3 0.2 0.3 0.2 0.2 0.2 0.  0.4 0.2 0.2 0.2 0.1 0.2 0.2 0.1 0.3
 0.3 0.2 0.3 0.3 0.3 0.4 0.3 0.3 0.3 0.3 0.2 0.2 0.2 0.2 0.2 0.3 0.2 0.2
 0.3 0.3 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.4 0.4 0.1 0.2 0.2 0.2 0.4 0.3
 0.3 0.3 0.2 0.2 0.1 0.2 0.3 0.2 0.3 0.2 0.3 0.3 0.2 0.2 0.3 0.2 0.3 0.2
 0.2 0.3 0.2 0.3 0.2 0.3 0.2 0.2 0.2 0.2 0.1 0.2 0.2 0.3 0.3 0.4 0.4 0.2
 0.3 0.3 0.4 0.2 0.3 0.1 0.3 0.3 0.2 0.2 0.2 0.4 0.2 0.3 0.1 0.1 0.2 0.2
 0.3 0.2 0.3 0.2 0.3 0.1 0.3 0.2 0.2 0.3 0.3 0.3 0.3 0.1 0.1 0.1 0.2 0.2
 0.2 0.3 0.2 0.3 0.2 0.3 0.2 0.2 0.1 0.2 0.4 0.2 0.

5. Broadcasting Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.

In [27]:

# print(data['horsepower'].isna().sum())

# new_hp=data['horsepower'].to_numpy().astype(float)
# nan_count=np.isnan(new_hp).sum()
# print(f'nan total copunt : {nan_count}')
# # calculate the mean while ignoring NaNs
# column_mean = np.nanmean(new_hp)
# # find all NaN positions using a boolean mask
# mask=np.isnan(new_hp)
# # replace the NaN values with the mean
# new_hp[mask]=np.round(column_mean,2)
# new_hp
# # new_hp=new_hp.astype(float)
# # new_hp=new_hp+(new_hp*0.1)
# # new_hp


In [8]:
# load data, converting '?' to NaN automatically
df = pd.read_csv('auto-mpg.csv', na_values='?')

# fill missing horsepower values with the mean
# pandas .mean() automatically ignores NaNs by default
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

# create a NEW NumPy array with the 10% increase
updated_hp_array = (df['horsepower'] * 1.10).to_numpy()

print(f"Updated Array Type: {type(updated_hp_array)}")
print("First 5 updated values:", updated_hp_array[:10])

Updated Array Type: <class 'numpy.ndarray'>
First 5 updated values: [143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209. ]


6. Boolean Indexing <br>Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing.

In [9]:

# extract the displacement and origin columns
displacement=df.iloc[:, 2]

origin = df.iloc[:,7]

# use boolean indexing to filter displacement where origin is 2
# This creates a sub-array containing only European car displacements
europe_disp = displacement[origin == 2]
# print(europe_disp)
# calculate the average
average_disp = np.mean(europe_disp)

print(f"Average Displacement for Origin 2 (Europe): {average_disp:.2f}")

Average Displacement for Origin 2 (Europe): 109.14


7. Matrix Operations<br> Create a 2D NumPy array containing the columns mpg, horsepower, and weight. Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [10]:
# load the entire file (handling '?' as NaN)
full_data = np.genfromtxt('auto-mpg.csv', delimiter=',', skip_header=1,
missing_values='?', filling_values=np.nan)

# slice the specific columns: mpg (0), horsepower (3), weight (4)
# use a list of indices [0, 3, 4] for the column part of the slice
new_2d_array = full_data[:, [0, 3, 4]]

print("First 3 rows of the new array:")
print(new_2d_array[:3])
weights_vector = np.array([1, 0.5, -0.2])
result = np.dot(new_2d_array, weights_vector)
print("First 5 weighted results:", result[:5])


First 3 rows of the new array:
[[  18.  130. 3504.]
 [  15.  165. 3693.]
 [  18.  150. 3436.]]
First 5 weighted results: [-617.8 -641.1 -594.2 -595.6 -602.8]


8. Sorting Use NumPy <br>Use NumPy to sort the cars by model_year in descending order and display the first five car names.

In [22]:
# model_year=df.iloc[:, 6]
# desc_data=np.sort(model_year)[::-1]
# print(desc_data)
desc_data=np.sort(df['model year'].values)[::-1]
desc_index_no=np.argsort(df['model year'].values)[::-1]
#desc_index_no
car_names=df['car name'].values
print(car_names[:5])

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype=object)

9. Correlation<br> Compute the Pearson correlation coefficient between mpg and weight using NumPy.

In [27]:
mpg_data=df['mpg']
weight_data=df['weight']
correlation_matrix=np.corrcoef(mpg_data,weight_data)
persone_coef=correlation_matrix[0,1]
print(f'Pearson correlation coefficient : {persone_coef:.2f}')


Pearson correlation coefficient : -0.83


10. Conditional Aggregates <br>Calculate the mean mpg for cars grouped by the number of cylinders using NumPy techniques.
1

In [47]:
mpg_data
cylinders_data=df['cylinders']
unique_cylinders=np.unique(cylinders_data)
#unique_cylinders
output_results = []

for cylinder_count in unique_cylinders:
    mean_mpg = np.mean(mpg_data[cylinders_data == cylinder_count])
    results = f"Cylinders: {int(cylinder_count)}- Average MPG: ~{mean_mpg:.2f}"
    output_results.append(results)

results = "\n".join(output_results)
print(results)

Cylinders: 3- Average MPG: ~20.55
Cylinders: 4- Average MPG: ~29.29
Cylinders: 5- Average MPG: ~27.37
Cylinders: 6- Average MPG: ~19.99
Cylinders: 8- Average MPG: ~14.96


#### Pandas Problems

1. Basic Exploration Load the dataset into a Pandas DataFrame. <br>Display:<br>
○ The first 10 rows<br>
○ The total number of rows and columns<br>
○ Summary statistics for numerical columns

In [54]:
import pandas as pd
df = pd.read_csv('auto-mpg.csv')
print(df.head(10))

shape_of=df.shape
print(f'Row count : {shape_of[0]} , Column count : {shape_of[1]}')

print(df.describe())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

2. Filtering and Indexing<br> Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.

In [65]:
df['car name']
df['model year']==75
df['weight']<3000
mask=(df['model year']==75) & (df['weight']<3000)
print(df.loc[mask,['car name','weight','mpg']])

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


3. Handling Missing Data<br> Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [76]:
df = pd.read_csv('auto-mpg.csv', na_values='?')
# rows_with_question_mark = df[df['horsepower'].str.contains(r'\?', regex=True)]

# print(rows_with_question_mark)
print(df.isnull().sum().sum())
#df.isna().sum()
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())
print(df['horsepower'].isnull().sum().sum())

6
0


4. Data Transformation <br>Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [79]:
df['power_to_weight_ratio']=round((df['horsepower'''])/(df['weight''']),3)
print(df.head(4))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu                  0.037  
1          70       1          buick skylark 320                  0.045  
2          70       1         plymouth satellite                  0.044  
3          70       1              amc rebel sst                  0.044  


5. Group By<br> Group the cars by origin and calculate the mean mpg for each group.


In [84]:
print(df.groupby('origin')['mpg'].mean())

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


6. Sorting <br>Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [96]:
#np.sort(df['mpg'])
#np.sort(df['mpg'])[::-1]
print(np.sort(df['mpg'])[::-1][:10])
top_10_cars = df.nlargest(10, 'mpg')[['car name','mpg']]
print(top_10_cars)

[46.6 44.6 44.3 44.  43.4 43.1 41.5 40.9 40.8 39.4]
                            car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4


7. Apply Function <br>Create a new column performance_score using a custom function: <br>def performance_score(row):<br>
return row['mpg'] * row['acceleration'] / row['weight']<br>Apply this function to each row and store the result in the new column.

In [99]:
def performance_score(row):
  return round(row['mpg'] * row['acceleration']/row['weight'],3)

df['performance_score']=df.apply(performance_score,axis=1)
print(df.head(4))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu                  0.037   
1          70       1          buick skylark 320                  0.045   
2          70       1         plymouth satellite                  0.044   
3          70       1              amc rebel sst                  0.044   

   performance_score  
0              0.062  
1              0.047  
2              0.058  
3              0.056  


8. Visualization Preparation<br> Generate a summary DataFrame with:<br>
○ Average mpg, weight, and horsepower for each model_year.

In [102]:
data_summary=round(df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean(),2)
print(data_summary)

              mpg   weight  horsepower
model year                            
70          17.69  3372.79      147.83
71          21.25  2995.43      106.95
72          18.71  3237.71      120.18
73          17.10  3419.02      130.48
74          22.70  2877.93       94.61
75          20.27  3176.80      101.07
76          21.57  3078.74      101.12
77          23.38  2997.36      105.07
78          24.06  2861.81       99.69
79          25.09  3055.34      101.21
80          33.70  2436.66       79.34
81          30.33  2522.93       81.84
82          31.71  2453.55       82.21


9. Exporting Data <br>Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV fi le named high_mpg_cars.csv.

In [106]:
subset = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]

# # Save to the Colab session storage
subset.to_csv('high_mpg_cars.csv', index=False)

# # Optional: Download the file to your computer immediately
from google.colab import files
files.download('high_mpg_cars.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

10. Finding Anomalies<br> Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifi cally:<br>
● Calculate the IQR for mpg.<br>
● Defi ne outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.<br>
● Create a DataFrame of cars classifi ed as outliers, displaying car_name, mpg, and model_year.

In [108]:
#df['mpg'].describe()
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)

# Interquartile Range (IQR)
IQR = Q3 - Q1

print(f"Q1 (25%): {Q1}")
print(f"Q3 (75%): {Q3}")
print(f"IQR: {IQR}")

Q1 (25%): 17.5
Q3 (75%): 29.0
IQR: 11.5


In [111]:
lower_values = Q1 - 1.5 * IQR
upper_values = Q3 + 1.5 * IQR
outliers = df[(df['mpg'] < lower_values) | (df['mpg'] > upper_values)]

print(f"Lower Values: {lower_values}")
print(f"Upper Values: {upper_values}")
print(f"Number of outliers found: {len(outliers)}")
print(outliers[['car name', 'mpg','model year']])

Lower Values: 0.25
Upper Values: 46.25
Number of outliers found: 1
      car name   mpg  model year
322  mazda glc  46.6          80
